### ISSUE TITLE
Abstimmung nächstes Team Meeting

### ISSUE THREAD

**Issue by banuguerel** [JuliusFaeustel/Paddlecs#14]
Folgende Terminvorschläge zum nächsten Teammeeting:

a) Do, 18:30 Uhr
b) Fr, 18:30 Uhr
c) Sa, 10:00 Uhr

Bitte mit den jeweiligen Buchstaben kommentieren. Der Termin mit den meisten Stimmen wird genommen. Anmerkung: Sollte man zu mehr als einem Termin zu Verfügung stehen, dann bitte auch alle Termine mit angeben!

**Comment by KennethKeil** [comment]
Mir ist es egal, ich kann nächste Woche zu allen 3 Terminen.

**Comment by JuliusFaeustel** [comment]
Bei mir geht nur Donnerstag

**Comment by s76527** [comment]
a und b

**Comment by concat1911** [comment]
a b c d
