### ISSUE TITLE
Web Server einrichten + Vertikaler Prototyp (kleine Demo)

### ISSUE THREAD

**Issue by s76527** [JuliusFaeustel/Paddlecs#6]
Ziel ist es, dass wir einen ersten funktionalen WebServer aufsetzen und anhand einer einfachen Demo (zb.HelloWorld Ausgabe) die Funktionalität des Servers testen

**Comment by KennethKeil** [comment]
Linh hat Erfahrungen mit Django, würde aber ggf. auch Spring lernen wollen, bzw. hat angeboten den WebServer mit aufzusetzen. Vllt. redet ihr zusammen mal, was ihr für den Server nutzen wollt. LG

**Comment by concat1911** [comment]
Wir brauchen keinen bezahlten Server für Prototypen:
- Für Backen können wir Heroku verwenden
- Für Frontend reicht netlify aus

**Comment by KennethKeil** [comment]
@s76527 und @concat1911 wollt ihr zusammen besprechen, wer die erste Demo aufsetzt?

**Comment by concat1911** [comment]
hab ich schon, keine Sorge!

**Comment by s76527** [comment]
hmm, ich habe jetzt auch schon eine kleine Demo vorbereitet^^

**Comment by KennethKeil** [comment]
Deswegen solltet ihr euch auch absprechen haha :'D

Naja nicht schlimm. Was habt ihr jetzt genau gebaut, bzw. aufgesetzt? Wollen wir uns das am Donnerstag anschauen?

**Comment by s76527** [comment]
Ich habe, wie Julius vorgeschlagen hat, mir mal Spring Boot angeschaut und damit ein kleines Demoprojekt erstellt, die eine REST-API bereit stellt. Für einen vertikalen Prototypen fehlt aber noch eine Datenbankanbindung. Die würde ich aber heute Abend noch integrieren.

**Comment by JuliusFaeustel** [comment]
Lob Lob lob

**Comment by KennethKeil** [comment]
Okay wunderbar! 

@s76527 Kannst du im Ordner Prototyp einen Unterordner "Web-Server" erstellen und dort das alles rein pushen? Ggf. kann @concat1911 Linh das gleiche machen, dann haben wir 2 Versionen für einen Web-Server und können schauen, welche wir nutzen wollen. Bzw. wäre es gut, wenn ihr euch intern absprecht, welche Variante ihr dann verwenden möchtet.
